channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0
- mlflow==2.20.0
- cloudpickle==3.1.1
- numpy==2.2.2
- psutil==6.1.1
- pip:
  - packaging==24.2
  - pandas==2.2.3
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
